no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = true
low_vram = false

###### huggingface ######
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""

max_bucket_reso = 2048
max_data_loader_n_workers = 2
max_grad_norm = 0.9
max_token_length = 75
min_bucket_reso = 256
mixed_precision = "bf16"
bf16 = true
fp16 = false
no_half_vae = true
output_dir = "test_sdxl_sd3"
output_name = "last"
pretrained_model_name_or_path = ""
prior_loss_weight = 0.4
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
full_fp16 = false
train_data_dir = "img"
training_comment = ""
xformers = true

###### steps and epochs ######
max_train_epochs = 20
save_every_n_epochs = 10

###### loss function ######
loss_type = "l2"

###### batch size ######
train_batch_size = 4
gradient_accumulation_steps = 1

###### optimizer ######
optimizer_type = "lion"
optimizer_args = [ "weight_decay=0.0005", "betas=(0.95, 0.99)" ]
unet_lr = 3e-5
text_encoder_lr = 2e-6

###### lr scheduler ######
lr_scheduler = "cosine"
lr_warmup_steps = 25
min_lr_ratio = 0.1

###### noise offset ######
noise_offset_type = "Multires"
multires_noise_iterations = 6
multires_noise_discount = 0.3
noise_offset_dynamic = true

###### misc ######
network_alpha = -1
network_dim = -1
network_module = "networks.lora"
network_args = []
network_dropout = 0
caption_dropout_rate = 0
clip_skip = 2
max_timestep = 1000
min_snr_gamma = 3.5
scale_weight_norms = 5
seed = 2951032221
